simulate_multiple_months: FALSE # if true, the simulation will be repeated for [simulation steps] times
simulation_steps: 100 # The amount of months to be simulated, if [simulate_multiple_months] is TRUE
comparison_simulation: TRUE # if true, two simulations will be run and compared

thermostat_type: "SIMPLE" # The type of thermostat to be used
second_thermostat_type: "PEERREVIEW" # The type of thermostat to be used when comparing two thermostats

############################
##### Thermostat types #####   Insert the titles in the above "Thermostat type" field
############################

# # # SIMPLE
# Simple thermostat that always accepts the new configuration

# # # OPPORTUNIST 
# Thermostat that buys cheap energy

# # # DESPERATION 
# Thermostat that becomes willing to spend more money on energy the higher the temperature is

# # # DESPERATION_OPPORTUNIST
# Thermostat that buys cheap energy and becomes willing to spend more money on energy the higher the temperature is

# # # PEERREVIEW
# Thermostat that buys energy if it is cheaper than the averate around it.

# # # PARTITION
# Thermostat that buys all the cheapest energy within a specified ranges

# # # DESPERATION_EXPONENTIAL
# Thermostat that becomes willing to spend more money on energy the higher the temperature is, exponentially

