doctest: "Test string"
Thermostat type: "OPPORTUNIST" # Supports: "SIMPLE", ""
Simulation steps: 100

SIMPLE: # The basic thermostat, turns on when the temperature is above 5 degrees
  TEMP: 5

OPPORTUNIST:
  LOW_TEMP: 3.6
  HIGH_TEMP: 6
  PRICE_OPPORTUNITY_THRESHOLD: 2
